language: python

before_script:
- test/create_config.sh
- pip install tox

# test script
script:  tox

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.2
      env: TOXENV=py32
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: pypy
      env: TOXENV=pypy
    - python: 2.7
      env: TOXENV=lint
    - python: 3.5
      env: TOXENV=lint
    - env: TOXENV=coverage
  fast_finish: true
  allow_failures:
    - python: 3.2
      env: TOXENV=py32
    - python: 2.7
      env: TOXENV=lint
    - python: 3.5
      env: TOXENV=lint

sudo: false
